// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// <define:import.meta.env>
var define_import_meta_env_default = { VITE_SUPABASE_PROJECT_ID: "ujjbslqbzhbjffoomipm", VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqamJzbHFiemhiamZmb29taXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNjIxODYsImV4cCI6MjA5NTYzODE4Nn0.XdFD2OJB2uHRXKJTE7zafoRBvoKCnJKZY1797vuppgI", VITE_SUPABASE_URL: "https://ujjbslqbzhbjffoomipm.supabase.co", VITE_WHATSAPP_NUMBER: "5511999999999", VITE_WHATSAPP_MESSAGE: "Ol\xE1! Gostaria de saber mais sobre os produtos da loja Artes Ind\xEDgenas.", VITE_GOOGLE_SPREADSHEET_ID: "1Q-WB2FsC-M3aRz9LdSdacoBKYccz2SgKUjfsE13XQUo", VITE_GOOGLE_SPREADSHEET_TAB: "Produtos", VITE_GOOGLE_SPREADSHEET_CONTENT_TAB: "Conteudo_Site", VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqamJzbHFiemhiamZmb29taXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNjIxODYsImV4cCI6MjA5NTYzODE4Nn0.XdFD2OJB2uHRXKJTE7zafoRBvoKCnJKZY1797vuppgI", MODE: "production", BASE_URL: "/", DEV: false, PROD: true, SSR: false };

// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/shared.ts
var truthy = (v) => {
  if (v === void 0 || v === null) return false;
  const s = String(v).trim().toLowerCase();
  return s === "true" || s === "1" || s === "yes" || s === "sim" || s === "y" || s === "verdadeiro";
};
var pick = (row, ...keys) => {
  for (const k of keys) {
    const v = row[k];
    if (v !== void 0 && v !== null && String(v).trim() !== "") return String(v).trim();
  }
  return "";
};
function siteOrigin() {
  return define_import_meta_env_default.VITE_PUBLIC_SITE_URL ?? "https://loja-comunitaria.lovable.app";
}
function rowToProduct(row) {
  const id = Number.parseInt(pick(row, "id"), 10);
  const name = pick(row, "name", "nome");
  const price = Number.parseFloat(
    pick(row, "price", "price_brl", "preco", "preco_brl").replace(",", ".")
  );
  if (!Number.isFinite(id) || !name || !Number.isFinite(price)) return null;
  const activeRaw = pick(row, "active", "ativo");
  const active = activeRaw === "" ? true : truthy(activeRaw);
  if (!active) return null;
  const qRaw = pick(row, "quantity", "stock_quantity", "quantidade_estoque");
  const quantity = qRaw ? Number.parseInt(qRaw, 10) : void 0;
  return {
    id,
    name,
    price,
    image: pick(row, "image", "image_url", "url_imagem") || "",
    description: pick(row, "description", "descricao", "short_description", "descricao_curta"),
    longDescription: pick(row, "longDescription", "details", "full_description", "detalhes") || void 0,
    category: pick(row, "category", "categoria") || void 0,
    featured: truthy(pick(row, "featured", "destaque")),
    quantity,
    materials: pick(row, "materials", "materiais") || void 0,
    peopleOrCommunity: pick(row, "people_or_community", "povo_ou_comunidade") || void 0,
    originLocation: pick(row, "origin_location", "local_de_origem") || void 0,
    dimensions: pick(row, "dimensions", "dimensoes") || void 0,
    productUrl: `${siteOrigin()}/produto/${id}`
  };
}
async function fetchProducts() {
  const spreadsheetId = "1Q-WB2FsC-M3aRz9LdSdacoBKYccz2SgKUjfsE13XQUo";
  const tab = "Produtos";
  if (!spreadsheetId) return [];
  const res = await fetch(`https://opensheet.elk.sh/${spreadsheetId}/${tab}`);
  if (!res.ok) throw new Error(`Failed to fetch products sheet: HTTP ${res.status}`);
  const rows = await res.json();
  return rows.map(rowToProduct).filter((p) => p !== null);
}
async function fetchStoreContact() {
  const spreadsheetId = "1Q-WB2FsC-M3aRz9LdSdacoBKYccz2SgKUjfsE13XQUo";
  const contentTab = "Conteudo_Site";
  const envNumber = "5511999999999";
  const envMessage = "Ol\xE1! Gostaria de saber mais sobre os produtos da loja Artes Ind\xEDgenas.";
  const contact = {
    siteUrl: siteOrigin(),
    whatsappNumber: envNumber,
    whatsappLink: envNumber ? `https://wa.me/${envNumber}${envMessage ? `?text=${encodeURIComponent(envMessage)}` : ""}` : ""
  };
  if (!spreadsheetId) return contact;
  try {
    const res = await fetch(`https://opensheet.elk.sh/${spreadsheetId}/${contentTab}`);
    if (!res.ok) return contact;
    const rows = await res.json();
    const map = {};
    for (const row of rows) {
      const k = (row.key ?? row.Key ?? row.chave ?? row.Chave ?? "").toString().trim();
      const v = (row.value ?? row.Value ?? row.valor ?? row.Valor ?? "").toString();
      if (k && v.trim()) map[k] = v;
    }
    const number = map.whatsapp_number || map.numero_whatsapp || envNumber;
    const message = map.whatsapp_message || map.mensagem_whatsapp || envMessage;
    contact.whatsappNumber = number;
    contact.whatsappLink = number ? `https://wa.me/${number}${message ? `?text=${encodeURIComponent(message)}` : ""}` : "";
    contact.email = map.email || void 0;
    contact.location = map.location || map.localizacao || void 0;
    contact.businessHours = map.business_hours || map.horario_atendimento || void 0;
    contact.instagramUrl = map.instagram_url || map.url_instagram || void 0;
    contact.facebookUrl = map.facebook_url || map.url_facebook || void 0;
  } catch {
  }
  return contact;
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List active products from the Loja Comunit\xE1ria catalog. Optionally filter to featured items or by category, and limit the number of results.",
  inputSchema: {
    featuredOnly: z.boolean().optional().describe("If true, only return products marked as featured/destaque."),
    category: z.string().optional().describe("Case-insensitive category filter (e.g. 'cestaria', 'colares')."),
    limit: z.number().int().positive().max(100).optional().describe("Maximum number of products to return. Default: all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ featuredOnly, category, limit }) => {
    let products = await fetchProducts();
    if (featuredOnly) products = products.filter((p) => p.featured);
    if (category) {
      const c = category.toLowerCase();
      products = products.filter((p) => (p.category ?? "").toLowerCase() === c);
    }
    if (limit) products = products.slice(0, limit);
    return {
      content: [
        {
          type: "text",
          text: `${products.length} produto(s) encontrado(s).

${products.map((p) => `#${p.id} \u2014 ${p.name} \u2014 R$ ${p.price.toFixed(2)} \u2014 ${p.productUrl}`).join("\n")}`
        }
      ],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Get full details for a single product by its numeric id.",
  inputSchema: {
    id: z2.number().int().positive().describe("Product id (matches the 'id' column in the catalog).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ id }) => {
    const products = await fetchProducts();
    const product = products.find((p) => p.id === id);
    if (!product) {
      return {
        content: [{ type: "text", text: `Nenhum produto encontrado com id ${id}.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_products_default = defineTool3({
  name: "search_products",
  title: "Search products",
  description: "Search the catalog by keyword. Matches product name, description, category, materials and community/people of origin.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Search terms (Portuguese or English)."),
    limit: z3.number().int().positive().max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const q = query.toLowerCase();
    const all = await fetchProducts();
    const matches = all.filter((p) => {
      const hay = [
        p.name,
        p.description,
        p.longDescription,
        p.category,
        p.materials,
        p.peopleOrCommunity,
        p.originLocation
      ].filter(Boolean).join(" ").toLowerCase();
      return hay.includes(q);
    });
    const results = matches.slice(0, limit ?? 20);
    return {
      content: [
        {
          type: "text",
          text: `${results.length} de ${matches.length} resultado(s) para "${query}".

${results.map((p) => `#${p.id} \u2014 ${p.name} \u2014 R$ ${p.price.toFixed(2)} \u2014 ${p.productUrl}`).join("\n")}`
        }
      ],
      structuredContent: { results, totalMatches: matches.length }
    };
  }
});

// src/lib/mcp/tools/get-store-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_store_contact_default = defineTool4({
  name: "get_store_contact",
  title: "Get store contact",
  description: "Return the store's public contact info: website URL, WhatsApp number and link, email, location, business hours, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const contact = await fetchStoreContact();
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: { contact: { ...contact } }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "loja-comunitaria-mcp",
  title: "Loja Comunit\xE1ria MCP",
  version: "0.1.0",
  instructions: "Ferramentas p\xFAblicas para consultar o cat\xE1logo da Loja Comunit\xE1ria (artesanatos ind\xEDgenas). Use `list_products` para listar o cat\xE1logo, `search_products` para buscar por palavra-chave, `get_product` para detalhes completos de um item, e `get_store_contact` para obter WhatsApp, email e demais canais da loja.",
  tools: [list_products_default, search_products_default, get_product_default, get_store_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
